Demo: Code coverage failure

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -59,15 +59,6 @@ jobs:
         result-format: 'cobertura'
         report-path: 'coverage'
         report-file-filter: '.*.xml'
-    - name: Check Code Coverage
-      run: |
-        echo "Code Coverage = ${{ steps.coverage-result-cobertura.outputs.code-coverage }}"
-        CODE_COVERAGE=${{ steps.coverage-result-cobertura.outputs.code-coverage }}
-        if [ $CODE_COVERAGE -lt 90 ]
-          then
-            echo "Code Coverage is below threshold - 90"
-            exit 1
-        fi
     - name: Create Issue in Case of Test Case failures
       if: steps.test-result-junit.outputs.failed-tests != '0'
       uses: maxkomarychev/oction-create-issue@v0.7.1
@@ -77,3 +68,17 @@ jobs:
         title: "Automatic Issue: Unit Test Failures"
         body:  ${{ steps.test-result-junit.outputs.issue-body }}
         labels: "bug"
+    - name: Check Code Coverage and fail if below threshold
+      run: |
+        echo "Code Coverage = ${{ steps.coverage-result-cobertura.outputs.code-coverage }}"
+        CODE_COVERAGE=${{ steps.coverage-result-cobertura.outputs.code-coverage }}
+        if [ $CODE_COVERAGE -lt 90 ]
+          then
+            echo "Code Coverage is below threshold - 90"
+            exit 1
+        fi
+    - name: Check Unit Test and fail if failures
+      if: steps.test-result-junit.outputs.failed-tests != '0'
+      run: |
+        echo "Failed Test Cases = ${{steps.test-result-junit.outputs.failed-tests}}"
+        exit 1
